### ISSUE TITLE
Semantic Analysis using AGDISTIS

### ISSUE THREAD

**Issue by suryahub** [AKSW/AGDISTIS#18]
Hi,
 I need to semantically analyse the following sentences
1. Adams is a famous singer
2. Adams is a famous Chess player
   When i input sentence 1. Adams should give dbpedia urls corresponding to Bryan Adams the famous singer and when sentence 2 is inputted Adams should give urls corresponding Michael Adams the famous Chess player.Is it possible to achieve such a usecase with AGDISTIS?Are there any other frameworks through which I can achieve the same?
   Regards
   suryahub

**Comment by D063520** [comment]
Hi,

so as far as I know there is no tool doing that. The problem is that Adam is highly ambiguous. In the english DBpedia there are 983 persons whos surname is Adam. Generally a tools expands the words with all possible meenings and then tries to find the right one. But I'm not aware of a tool expanding so much, i.e. if the sentence contains "Elisabeth" take into consideration all persons called "Elisabeth".

Even if this would be the case AGDISTIS is the wrong tool for you. The decision between the right Adams is token base on the occurrence of other NE. Here there is only one. The words "famous singer" and "chess player" will be ignored by AGDISTIS. DBpedia spotlight would do that, but as I said, "Adams" is to ambiguous. I tried, DBpedia Spotlight fails.

Good Luck
Dennis

**Comment by DiegoMoussallem** [comment]
As @D063520 said, the both sentences are very ambiguous. We intend to be able to tackle it in the new version of AGDISTIS.  But, AGDISTIS doesn't provide it to you nowadays.

**Comment by RicardoUsbeck** [comment]
Dear all, 

indeed, AGDISTIS cannot solve that currently. @DiegoMoussallem is working on an extension based on contextual text similarity to improve this. Stay tuned for updates which hopefully will come very soon. 

Best 
Ricardo
